apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-k8s-deployment
  namespace: lab-k8s
  labels:
    app: demo-k8s
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-k8s
  template:
    metadata:
      labels:
        app: demo-k8s
    spec:
      containers:
        - name: demo-k8s-container
          image: demo-k8s:1.0.0
          imagePullPolicy: Never
          ports:
            - containerPort: 8084
          env:
            - name: APP_MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: demo-k8s-config
                  key: app.message
          readinessProbe:
            httpGet:
              path: /api/hello
              port: 8084
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/hello
              port: 8084
            initialDelaySeconds: 20
            periodSeconds: 10